# ===============================
# SERVER CONFIG
# ===============================
server.port=8082

# ===============================
# DATABASE CONFIG (Oracle - XEPDB1)
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=flight_user
spring.datasource.password=flight123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ===============================
# THYMELEAF CONFIG
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ===============================
# LOGGING (optional but useful)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer config
spring.kafka.consumer.group-id=flight-group-new1

# Deserializer (JSON → Object)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Important for JSON
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.flightapp.flight_service.event.BookingEvent

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer